# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
appVersion: 9.4.7
description: A Helm chart for Grafana
name: grafana
version: 1.3.0
kubeVersion: '>=v1.23.0-0,<v1.27-0'
dependencies:
- name: grafana
  version: 6.53.0
  repository: https://grafana.github.io/helm-charts
- name: ingress
  version: '*'
  repository: file://../../../base/ingress/
