# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v1
kind: ConfigMap
metadata:
  name: remoting-execution-server
  labels:
    app: remoting-execution-server
    chart: {{ .Chart.Name  }}
    heritage: {{ .Release.Service }}
    toolchain_product: "remote-cache"
data:
  execution.yaml: |
    listen_address: 0.0.0.0:8980
    cas:
      address: {{ $.Values.cas_address }}
      connections: 16
    infra:
      sentry_dsn: {{ $.Values.server_sentry_dsn }}
