# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

{{ $values := merge (dict) .Values.workers.fetcher_values .Values }}
{{- with merge (dict "Values" $values) . -}}
{{- template "workflow.worker.resources" . -}}
{{- end -}}
