# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

{{- if .Values.slack_webhook }}
apiVersion: v1
kind: Secret
metadata:
  name: remote-cache-usage-reporter-slack-webhook
  labels:
    services: toolchain
type: Opaque
data:
  secret_string: {{ .Values.slack_webhook | b64enc }}
{{- end }}