# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
description: Buildsense workflow services (worker + maintenance)
name: buildsense-workflow
version: 1.2.0
kubeVersion: '>=v1.24.0-0,<v1.28-0'
dependencies:
- name: workflow
  version: '*'
  repository: file://../../../../base/workflow/
