# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).
external-dns:
    txtOwnerId: kramer
    serviceAccount:
        annotations:
            eks.amazonaws.com/role-arn: costanza-arn
