# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
description: SCM Integration internal/private API service
name: scm-integration-api
version: 1.2.0
kubeVersion: '>=v1.24.0-0,<v1.28-0'
dependencies:
- name: django
  version: '*'
  repository: file://../../../../base/django/
