# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: creds-rotator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update", "patch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rotator-job-user
---
 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: creds-rotator-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: creds-rotator-role
subjects:
- kind: ServiceAccount
  name: rotator-job-user
  namespace: {{ .Release.Namespace }}
 