# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
name: remote-cache-usage-reporter
description: Calculate and report on remote cache usage
version: 0.11.0
kubeVersion: '>=v1.23.0-0,<v1.27-0'