# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1"  }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: remoting-proxy-server
  labels:
    services: toolchain-monitoring
spec:
  endpoints:
    - port: metrics
      path: "/metricsz"
      interval: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: remoting-proxy-server
      monitor: "true"
{{- end }}
