# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v1
kind: Service
metadata:
  name: 'opensearch-dev-proxy'
  labels:
    app: {{  .Chart.Name  }}
    chart: {{  .Chart.Name  }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service_port }}
      targetPort: 9200
      protocol: TCP
      name: opensearch-dev-proxy
  selector:
    app: {{  .Chart.Name  }}
    release: {{ .Release.Name }}
