# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
appVersion: 0.25.0
description: Open Telemetry Collector
name: opentelemetry
version: 0.8.0
home: https://opentelemetry.io/
