# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
description: Posthog analytics deployment [dev-only]
name: posthog
version: 0.2.0
appVersion: 1.29.1
kubeVersion: '>=v1.21.0-0,<v1.25-0'
