# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

name: users-api
toolchain_product_name: users
dbs: [users]
secrets:
- jwt-auth-secret-key
service_type: api
iam_service_role_arn: null
extra_config:
  LOGIN_URL_HOST: app.toolchain.com
  REMOTE_CACHE_ADDRESS: cache.toolchain.com:443  # modified by install script
  REMOTE_EXECUTION_CUSTOMER_SLUGS: [] # modified by install script

resources:
  gunicorn:
    requests:
      cpu: 100m
      memory: 512Mi
gunicorn_image_rev:
  us-east-1: prod-2023-05-08.12-24-16-d0d6683b1814
