# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
description: AWS OpenSearch proxy for dev
name: opensearch-dev-proxy
version: 1.0.0
kubeVersion: '>=v1.24.0-0,<v1.28-0'
