# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).
aws_region: us-east-1
logging_opensearch_host: davola.domain.local
toolchain_env: toolchain_prod
fluent-bit:
  serviceMonitor:
    enabled: true
  config:
     outputs: |
        [OUTPUT]
            Name  opensearch
            Host  davola.domain.local
            Port  443
            Logstash_Format On
            Suppress_Type_Name On
            Time_Key @timestamp
            Replace_Dots On
            Logstash_Prefix prod-logs
            tls On
            AWS_Auth On
            AWS_Region us-east-1
curator:
  enabled: true
  iam_role_arn: arn:aws:cosmo
  image: kramer
