# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).
# Copyright {{ copyright_year }} Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

{% raw %}
{{- template "django.service.resources" . -}}
{% endraw %}
