# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
description: Notifications internal/private API service
name: notifications-api
version: 0.1.0
kubeVersion: '>=v1.24.0-0,<v1.28-0'
dependencies:
- name: django
  version: '*'
  repository: file://../../../../base/django/
