# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
appVersion: v2.43.0
description: Basic prometheus server to run in dev cluster
name: dev-prometheus
version: 0.8.0
kubeVersion: '>=v1.24.0-0,<v1.28-0'
dependencies:
- name: prometheus
  version: 20.2.0
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-adapter
  # prometheus-adapter app version: 0.10.0 https://github.com/kubernetes-sigs/prometheus-adapter)
  version: 4.1.1
  repository: https://prometheus-community.github.io/helm-charts
  condition: features.prometheusAdapter
