# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
appVersion: '1.0'
description: Copy PyPi DB data from prod to dev.
name: pypi-db-snapshot-copier
version: 0.12.0
kubeVersion: '>=v1.21.0-0,<v1.25-0'
