# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

global:
  region: us-east-1
gunicorn_image_rev:
  us-east-1: george
server_sentry_dsn: test
iam_service_role_arn: arn::bob::jerry.nbc-seinfeld.cosmo
toolchain_env: toolchain_prod
ingress:
  logs_prefix: hello-newman-1
  enabled: true
  external_ingress_sg_id:
      us-east-1: jerry
  ssl_certificate_arn:  
    us-east-1: david-puddy
