# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).
influxdb2:
  nodeSelector:
      toolchain.instance_category: jerry
  persistence:
    size: 200Gi