# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v2
description: A Helm chart containing templates for use by charts defining workflow services.
name: workflow
version: 1.4.0