# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

global:
  region: us-east-1
gunicorn_image_rev:
  us-east-1: george
server_sentry_dsn: test
replicas: 2
toolchain_env: toolchain_prod
tests:
  enabled: true
  webhooks:
    image_rev:
      us-east-1: ocean-called
ingress:
  enabled: true
  external_ingress_sg_id:
    us-east-1: no-soup-for-you
  logs_prefix: prod-e1-1
  rules:
  - host: webhooks.toolchain.com
    http:
      paths:
      - backend:
          service:
              name: webhooks
              port: 
                  number: 80
        path: /
        pathType: Prefix
  scheme: internet-facing
  ssl_certificate_arn:
    us-east-1: arn:jambalaya
