# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

global:
  region: us-east-1
gunicorn_image_rev:
  us-east-1: george
ingress:
  enabled: false
server_sentry_dsn: test
toolchain_env: toolchain_dev
tests:
  enabled: true
  webhooks:
    image_rev:
      us-east-1: shrimp