# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-api-key
  labels:
    app: opentelemetry
type: Opaque
data:
  api_key: {{ .Values.honeycomb.apiKey | b64enc | quote }}
