# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1"  }}
{{ if .Values.serviceMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: monitor-{{ .Release.Namespace}}-{{ .Release.Name }}
  labels:
    services: toolchain-monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      # This will match the Service for both otel-collector and otel-agent.
      app: opentelemetry
  endpoints:
    - port: metrics
      path: "/metrics"
      interval: 10s
{{ end -}}
{{- end }}